

mysql: &mysql1
  adapter: mysql2
  database: "<%=ENV['OPENSHIFT_APP_NAME']%>"
  username: "<%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>"
  password: "<%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>"
  host:     <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>

mysql: &mysql2
  adapter: mysql2
  encoding: utf8
  database: signin
  pool: 5
  username: root
  password: amura123
  host: localhost

development:
  <<:  *mysql2

test: &test
  <<:  *mysql2

production:
  <<:  *mysql2
